import { Tool } from './types';

export const tools: Tool[] = [
  {
    id: 1,
    name: "ChatGPT",
    icon: "🤖",
    language: "한국어 지원",
    category: "글쓰기",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "대화형 AI로 글쓰기, 요약, 아이디어 생성 지원",
    tags: ["생산성", "문서", "아이디어"],
    filterTags: ["writing", "research", "free", "korean"],
    reason: "글쓰기와 아이디어 정리에 가장 범용적으로 활용",
    recommendFor: ["글쓰기", "리서치"],
    website: "https://chat.openai.com"
  },
  {
    id: 2,
    name: "Claude",
    icon: "✨",
    language: "한국어 지원",
    category: "문서분석",
    level: "입문",
    price: "무료/유료",
    priceType: "free",
    description: "Anthropic이 개발한 AI로 긴 문서 분석, 코드 생성, 복잡한 추론 작업에 강점이 있습니다. 안전성과 신뢰성을 강조하는 도구입니다.",
    tags: ["글쓰기", "리서치", "코딩"],
    filterTags: ["writing", "research", "free", "korean"],
    reason: "긴 문서 요약과 분석 중심 사용자를 위한 추천 카드로 적합합니다.",
    recommendFor: ["긴 보고서를 읽어야 하는 직장인", "정교한 논리가 필요한 연구자", "안전한 AI 답변을 원하는 분"],
    website: "https://claude.ai"
  },
  {
    id: 3,
    name: "Perplexity AI",
    icon: "🔎",
    language: "한국어 지원",
    category: "리서치",
    level: "입문",
    price: "무료/유료",
    priceType: "free",
    description: "실시간 웹 검색과 AI를 결합한 리서치 도구입니다. 출처를 인용하며 정보를 빠르게 찾아주는 데 강점이 있습니다.",
    tags: ["리서치", "검색", "요약"],
    filterTags: ["research", "free", "korean"],
    reason: "정보 탐색형 사용자 시나리오에서 클릭률을 높일 수 있는 추천 도구입니다.",
    recommendFor: ["팩트 체크가 중요한 분", "최신 뉴스를 자주 검색하는 분", "논문/보고서 출처가 필요한 학생"],
    website: "https://www.perplexity.ai"
  },
  {
    id: 4,
    name: "Notion AI",
    icon: "🗂️",
    language: "한국어 지원",
    category: "정리",
    level: "입문",
    price: "유료",
    priceType: "paid",
    description: "Notion 내부에서 문서 작성, 요약, 번역, 아이디어 브레인스토밍을 도와주는 AI입니다. 문서 관리형 사용 흐름에 적합합니다.",
    tags: ["글쓰기", "정리", "요약"],
    filterTags: ["writing", "paid", "korean"],
    reason: "문서 생산성과 협업 중심 사용자에게 잘 맞는 추천입니다.",
    recommendFor: ["노션으로 업무를 관리하는 팀", "문서 정리가 습관인 분", "회의록 요약이 필요한 직장인"],
    website: "https://www.notion.so/product/ai"
  },
  {
    id: 5,
    name: "Midjourney",
    icon: "🎨",
    language: "영어",
    category: "이미지 생성",
    level: "중급",
    price: "유료",
    priceType: "paid",
    description: "텍스트 기반 이미지 생성 AI",
    tags: ["이미지", "디자인", "아트"],
    filterTags: ["image", "paid"],
    reason: "아트 스타일 이미지 생성에 강점",
    recommendFor: ["이미지 생성"],
    website: "https://www.midjourney.com"
  },
  {
    id: 6,
    name: "DALL·E 3",
    icon: "🖼️",
    language: "한국어 지원",
    category: "이미지",
    level: "입문",
    price: "유료",
    priceType: "paid",
    description: "텍스트 설명만으로 이미지를 생성할 수 있는 OpenAI 이미지 생성 모델입니다. 비교적 쉽게 접근 가능한 이미지 생성 도구입니다.",
    tags: ["이미지", "생성", "디자인"],
    filterTags: ["image", "paid", "korean"],
    reason: "입문 사용자도 쉽게 이미지 생성 흐름을 체험할 수 있어 추천 카드로 적합합니다.",
    recommendFor: ["간단한 삽화가 필요한 블로거", "AI 이미지 생성이 처음인 입문자", "한글 프롬프트를 선호하는 분"],
    website: "https://openai.com/dall-e-3"
  },
  {
    id: 7,
    name: "GitHub Copilot",
    icon: "💻",
    language: "영어",
    category: "코딩",
    level: "중급",
    price: "유료",
    priceType: "paid",
    description: "개발자의 코딩을 실시간으로 도와주는 AI 페어 프로그래머입니다. 코드 자동 완성 및 제안 기능이 탁월합니다.",
    tags: ["코딩", "개발", "생산성"],
    filterTags: ["coding", "paid"],
    reason: "개발 생산성을 극대화하고자 하는 전문가들에게 필수적인 도구입니다.",
    recommendFor: ["반복적인 코딩을 줄이고 싶은 개발자", "새로운 언어를 배우는 프로그래머", "대규모 프로젝트를 진행하는 팀"],
    website: "https://github.com/features/copilot"
  },
  {
    id: 8,
    name: "Cursor",
    icon: "🚀",
    language: "영어",
    category: "코딩",
    level: "중급",
    price: "무료/유료",
    priceType: "free",
    description: "AI가 내장된 코드 에디터로, 전체 프로젝트 문맥을 이해하고 코드를 작성하거나 수정하는 데 최적화되어 있습니다.",
    tags: ["코딩", "에디터", "개발"],
    filterTags: ["coding", "free"],
    reason: "최신 AI 코딩 경험을 원하는 개발자들에게 가장 추천하는 에디터입니다.",
    recommendFor: ["AI와 긴밀하게 협업하고 싶은 개발자", "기존 VS Code 사용자", "빠른 프로토타이핑이 필요한 분"],
    website: "https://www.cursor.com"
  },
  {
    id: 9,
    name: "DeepL",
    icon: "🌐",
    language: "한국어 지원",
    category: "번역",
    level: "입문",
    price: "무료/유료",
    priceType: "free",
    description: "세계에서 가장 정확한 번역을 제공한다고 평가받는 AI 번역기입니다. 자연스러운 문맥 파악 능력이 뛰어납니다.",
    tags: ["번역", "언어", "글쓰기"],
    filterTags: ["writing", "free", "korean"],
    reason: "정확하고 자연스러운 번역이 필요한 모든 사용자에게 최고의 선택입니다.",
    recommendFor: ["자연스러운 번역이 필요한 번역가", "해외 자료를 자주 읽는 분", "비즈니스 메일을 작성하는 직장인"],
    website: "https://www.deepl.com"
  },
  {
    id: 10,
    name: "Zapier Central",
    icon: "⚙️",
    language: "영어",
    category: "자동화",
    level: "중급",
    price: "무료/유료",
    priceType: "free",
    description: "6,000개 이상의 앱을 연결하여 나만의 AI 에이전트를 만들고 업무 프로세스를 자동화할 수 있는 도구입니다.",
    tags: ["자동화", "워크플로우", "생산성"],
    filterTags: ["automation", "free"],
    reason: "복잡한 업무 프로세스를 자동화하려는 사용자에게 가장 강력한 솔루션입니다.",
    recommendFor: ["반복 업무를 자동화하고 싶은 기획자", "여러 앱을 연동해 사용하는 헤비 유저", "나만의 AI 비서를 만들고 싶은 분"],
    website: "https://zapier.com/central"
  },
  {
    id: 11,
    name: "Make",
    icon: "🔗",
    language: "영어",
    category: "자동화",
    level: "고급",
    price: "무료/유료",
    priceType: "free",
    description: "시각적인 드래그 앤 드롭 인터페이스로 복잡한 워크플로우를 설계하고 자동화할 수 있는 노코드 플랫폼입니다.",
    tags: ["자동화", "노코드", "개발"],
    filterTags: ["automation", "free"],
    reason: "고도화된 자동화 시나리오를 구축하려는 전문가들에게 적합한 도구입니다.",
    recommendFor: ["복잡한 로직의 자동화가 필요한 분", "노코드 툴에 익숙한 사용자", "데이터 파이프라인을 구축하려는 팀"],
    website: "https://www.make.com"
  },
  {
    id: 12,
    name: "Canva Magic Studio",
    icon: "🎨",
    language: "한국어 지원",
    category: "디자인",
    level: "입문",
    price: "무료/유료",
    priceType: "free",
    description: "디자인 초보자도 AI를 활용해 포스터, 프레젠테이션, SNS 게시물을 순식간에 제작할 수 있는 올인원 디자인 도구입니다.",
    tags: ["디자인", "이미지", "콘텐츠"],
    filterTags: ["image", "free", "korean"],
    reason: "전문 지식 없이도 수준 높은 디자인 결과물을 원하는 사용자에게 최고의 선택입니다.",
    recommendFor: ["SNS 마케팅 콘텐츠를 만드는 분", "발표 자료를 예쁘게 꾸미고 싶은 학생", "디자인 감각이 부족해 고민인 직장인"],
    website: "https://www.canva.com/magic-studio"
  },
  {
    id: 13,
    name: "Jasper",
    icon: "✍️",
    language: "영어",
    category: "글쓰기",
    level: "중급",
    price: "유료",
    priceType: "paid",
    description: "비즈니스 및 마케팅 글쓰기에 특화된 AI로, 브랜드 보이스를 학습하여 기업용 콘텐츠 제작을 돕습니다.",
    tags: ["글쓰기", "마케팅", "비즈니스"],
    filterTags: ["writing", "paid"],
    reason: "전문적인 마케팅 문구와 블로그 포스팅이 필요한 팀에게 추천합니다.",
    recommendFor: ["마케팅 카피라이터", "블로그 운영자", "일관된 브랜드 톤이 필요한 기업"],
    website: "https://www.jasper.ai"
  },
  {
    id: 14,
    name: "Replit AI",
    icon: "🌀",
    language: "영어",
    category: "코딩",
    level: "입문",
    price: "무료/유료",
    priceType: "free",
    description: "브라우저에서 바로 코딩하고 배포할 수 있는 환경에 AI가 결합되어, 초보자도 쉽게 웹사이트나 앱을 만들 수 있게 도와줍니다.",
    tags: ["코딩", "개발", "배포"],
    filterTags: ["coding", "free"],
    reason: "설치 없이 바로 코딩을 시작하고 AI의 도움을 받고 싶은 입문자에게 최적입니다.",
    recommendFor: ["코딩 공부를 시작하는 학생", "빠르게 아이디어를 구현하고 싶은 창업가", "환경 설정 없이 코딩하고 싶은 분"],
    website: "https://replit.com"
  },
  {
    id: 15,
    name: "Suno",
    icon: "🎵",
    language: "영어",
    category: "음악 생성",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "AI로 음악을 생성하는 플랫폼입니다. 텍스트 프롬프트만으로 고품질의 노래와 가사를 만들어낼 수 있습니다.",
    tags: ["음악", "생성AI", "크리에이티브"],
    filterTags: ["automation", "free"],
    reason: "텍스트로 음악을 만들 수 있음",
    recommendFor: ["음악 제작이 필요한 크리에이터", "나만의 노래를 만들고 싶은 분", "콘텐츠 배경음악이 필요한 분"],
    website: "https://suno.com"
  },
  {
    id: 16,
    name: "Pika",
    icon: "🎬",
    language: "영어",
    category: "영상 생성",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "AI 기반 영상 생성 도구로, 텍스트나 이미지를 고품질의 애니메이션 영상으로 변환해줍니다.",
    tags: ["영상", "생성AI", "콘텐츠"],
    filterTags: ["automation", "free"],
    reason: "텍스트로 영상 생성 가능",
    recommendFor: ["영상 콘텐츠 제작자", "애니메이션에 관심 있는 분", "광고 영상을 만들고 싶은 분"],
    website: "https://pika.art"
  },
  {
    id: 17,
    name: "Ideogram",
    icon: "🎨",
    language: "영어",
    category: "이미지 생성",
    level: "입문",
    price: "무료",
    priceType: "free",
    description: "텍스트 포함 이미지 생성에 특화된 AI입니다. 로고나 타이포그래피가 포함된 이미지를 정확하게 생성합니다.",
    tags: ["이미지", "디자인", "생성AI"],
    filterTags: ["image", "free"],
    reason: "텍스트 표현 이미지에 강함",
    recommendFor: ["로고 디자인이 필요한 분", "포스터 제작자", "타이포그래피 디자인이 필요한 분"],
    website: "https://ideogram.ai"
  },
  {
    id: 18,
    name: "PlayHT",
    icon: "🎙️",
    language: "영어",
    category: "음성 생성",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "AI 음성 생성 플랫폼으로, 매우 자연스러운 AI 음성을 생성하여 오디오북이나 팟캐스트 등에 활용할 수 있습니다.",
    tags: ["TTS", "음성", "콘텐츠"],
    filterTags: ["automation", "free"],
    reason: "자연스러운 AI 음성 생성",
    recommendFor: ["팟캐스트 제작자", "오디오북을 만들고 싶은 분", "영상 내레이션이 필요한 분"],
    website: "https://play.ht"
  },
  {
    id: 19,
    name: "Descript",
    icon: "✂️",
    language: "영어",
    category: "영상/음성 편집",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "AI 기반 영상 및 오디오 편집 도구입니다. 텍스트를 수정하듯 영상을 편집할 수 있는 혁신적인 기능을 제공합니다.",
    tags: ["편집", "콘텐츠", "생산성"],
    filterTags: ["automation", "free"],
    reason: "텍스트 기반 영상 편집",
    recommendFor: ["유튜버 및 영상 편집자", "팟캐스트 편집자", "빠른 영상 컷 편집이 필요한 분"],
    website: "https://www.descript.com"
  },
  {
    id: 20,
    name: "Synthesia",
    icon: "👤",
    language: "영어",
    category: "영상 생성",
    level: "중급",
    price: "유료",
    priceType: "paid",
    description: "AI 아바타 영상 생성 플랫폼입니다. 텍스트만 입력하면 실제 사람이 말하는 듯한 영상을 제작할 수 있습니다.",
    tags: ["영상", "아바타", "콘텐츠"],
    filterTags: ["automation", "paid"],
    reason: "AI 아바타 영상 제작에 특화",
    recommendFor: ["기업 교육 영상 제작자", "뉴스 형식의 콘텐츠를 만드는 분", "얼굴 노출 없이 영상을 만들고 싶은 분"],
    website: "https://www.synthesia.io"
  },
  {
    id: 21,
    name: "Tome",
    icon: "📊",
    language: "영어",
    category: "프레젠테이션",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "AI 기반 프레젠테이션 생성 도구입니다. 주제만 입력하면 슬라이드 구조와 내용을 자동으로 구성해줍니다.",
    tags: ["프레젠테이션", "문서", "생산성"],
    filterTags: ["writing", "free"],
    reason: "자동 슬라이드 생성",
    recommendFor: ["발표 자료를 빠르게 만들어야 하는 학생", "기획안 작성이 잦은 직장인", "스토리텔링형 문서를 만드는 분"],
    website: "https://tome.app"
  },
  {
    id: 22,
    name: "Gamma",
    icon: "🪄",
    language: "한국어 지원",
    category: "프레젠테이션",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "AI 프레젠테이션 제작 플랫폼입니다. 디자인 자동화 기능을 통해 세련된 슬라이드와 웹페이지를 빠르게 제작할 수 있습니다.",
    tags: ["슬라이드", "문서", "디자인"],
    filterTags: ["writing", "free", "korean"],
    reason: "디자인 자동화 슬라이드",
    recommendFor: ["디자인 감각이 부족한 발표자", "빠른 제안서 작성이 필요한 분", "웹 기반 프레젠테이션을 선호하는 분"],
    website: "https://gamma.app"
  },
  {
    id: 23,
    name: "Codeium",
    icon: "💻",
    language: "영어",
    category: "코딩/개발",
    level: "입문",
    price: "무료",
    priceType: "free",
    description: "개인 개발자에게 무료로 제공되는 강력한 AI 코드 추천 도구입니다. 다양한 IDE와 연동되어 코딩 속도를 높여줍니다.",
    tags: ["코딩", "개발", "자동완성"],
    filterTags: ["coding", "free"],
    reason: "무료 코드 추천 AI",
    recommendFor: ["무료 코딩 보조 도구를 찾는 개발자", "다양한 언어를 사용하는 프로그래머", "학습 중인 코딩 입문자"],
    website: "https://codeium.com"
  },
  {
    id: 24,
    name: "Phind",
    icon: "🔍",
    language: "영어",
    category: "코딩/검색",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "개발자용 AI 검색 엔진입니다. 기술적인 질문에 대해 정확한 답변과 코드 예시를 제공하며 최신 문서를 참조합니다.",
    tags: ["검색", "코딩", "개발"],
    filterTags: ["coding", "research", "free"],
    reason: "개발 질문에 최적화",
    recommendFor: ["에러 해결이 필요한 개발자", "새로운 기술 스택을 공부하는 분", "정확한 코드 예시가 필요한 분"],
    website: "https://www.phind.com"
  },
  {
    id: 25,
    name: "Recraft",
    icon: "🎨",
    language: "영어",
    category: "디자인",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "AI 디자인 생성 플랫폼으로, 벡터 그래픽과 일러스트레이션을 생성하고 편집하는 데 특화되어 있습니다.",
    tags: ["디자인", "이미지", "브랜딩"],
    filterTags: ["image", "free"],
    reason: "브랜드 디자인 생성",
    recommendFor: ["벡터 이미지가 필요한 디자이너", "일관된 스타일의 아이콘을 만드는 분", "브랜드 에셋 제작자"],
    website: "https://www.recraft.ai"
  },
  {
    id: 26,
    name: "Looka",
    icon: "🏷️",
    language: "영어",
    category: "브랜딩",
    level: "입문",
    price: "유료",
    priceType: "paid",
    description: "AI 로고 제작 플랫폼입니다. 브랜드 이름과 선호하는 스타일을 입력하면 수많은 로고 시안을 자동으로 생성합니다.",
    tags: ["로고", "브랜드", "디자인"],
    filterTags: ["image", "paid"],
    reason: "자동 로고 생성",
    recommendFor: ["1인 창업가", "빠르게 로고가 필요한 소상공인", "브랜드 아이덴티티를 고민 중인 분"],
    website: "https://looka.com"
  },
  {
    id: 27,
    name: "Brandmark",
    icon: "✨",
    language: "영어",
    category: "브랜딩",
    level: "입문",
    price: "유료",
    priceType: "paid",
    description: "AI 로고 및 브랜드 생성 도구입니다. 심플하고 현대적인 감각의 로고와 브랜드 가이드를 자동으로 만들어줍니다.",
    tags: ["로고", "디자인", "브랜드"],
    filterTags: ["image", "paid"],
    reason: "스타트업 브랜딩에 적합",
    recommendFor: ["스타트업 창업자", "깔끔한 로고 디자인을 선호하는 분", "브랜드 컬러 조합이 고민인 분"],
    website: "https://brandmark.io"
  },
  {
    id: 28,
    name: "Cleanup Pictures",
    icon: "🧹",
    language: "영어",
    category: "이미지 편집",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "이미지에서 원하지 않는 객체나 텍스트를 AI로 감쪽같이 제거해주는 도구입니다.",
    tags: ["이미지", "편집", "AI"],
    filterTags: ["image", "free"],
    reason: "이미지 보정에 유용",
    recommendFor: ["사진 보정이 필요한 일반인", "쇼핑몰 이미지 편집자", "불필요한 배경 요소를 지우고 싶은 분"],
    website: "https://cleanup.pictures"
  },
  {
    id: 29,
    name: "RemoveBG",
    icon: "✂️",
    language: "한국어 지원",
    category: "이미지 편집",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "이미지 배경 제거 AI입니다. 단 몇 초 만에 배경을 투명하게 만들어주며, 누끼 따기 작업의 필수 도구입니다.",
    tags: ["이미지", "편집", "디자인"],
    filterTags: ["image", "free", "korean"],
    reason: "배경 제거 자동화",
    recommendFor: ["누끼 작업이 많은 디자이너", "제품 사진을 편집하는 판매자", "합성 사진을 만드는 분"],
    website: "https://www.remove.bg"
  },
  {
    id: 30,
    name: "Fireflies",
    icon: "🔥",
    language: "영어",
    category: "회의 AI",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "회의 녹음 및 요약 AI입니다. 화상 회의에 참여하여 내용을 기록하고 핵심 내용을 요약해줍니다.",
    tags: ["회의", "생산성", "요약"],
    filterTags: ["automation", "free"],
    reason: "회의 기록 자동 생성",
    recommendFor: ["회의가 많은 팀장", "기록이 중요한 프로젝트 매니저", "다시 듣기 힘든 긴 회의를 하는 분"],
    website: "https://fireflies.ai"
  },
  {
    id: 31,
    name: "Otter AI",
    icon: "🦦",
    language: "영어",
    category: "회의 AI",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "회의 음성 기록 AI로, 실시간으로 대화를 텍스트로 변환하고 요약해주는 기능을 제공합니다.",
    tags: ["회의", "음성", "요약"],
    filterTags: ["automation", "free"],
    reason: "회의 기록 자동화",
    recommendFor: ["영어 회의가 잦은 직장인", "인터뷰 기록이 필요한 기자", "강의 내용을 기록하고 싶은 학생"],
    website: "https://otter.ai"
  },
  {
    id: 32,
    name: "Taskade",
    icon: "✅",
    language: "한국어 지원",
    category: "생산성",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "AI 기반 협업 도구로, 할 일 목록, 마인드맵, 채팅 등을 AI와 함께 관리할 수 있는 올인원 워크스페이스입니다.",
    tags: ["협업", "생산성"],
    filterTags: ["automation", "free", "korean"],
    reason: "팀 협업에 적합",
    recommendFor: ["팀 프로젝트를 관리하는 분", "AI와 함께 업무 계획을 세우고 싶은 분", "다양한 뷰로 업무를 보고 싶은 분"],
    website: "https://www.taskade.com"
  },
  {
    id: 33,
    name: "FlowGPT",
    icon: "🌊",
    language: "영어",
    category: "프롬프트",
    level: "입문",
    price: "무료",
    priceType: "free",
    description: "AI 프롬프트 공유 플랫폼입니다. 전 세계 사용자들이 만든 창의적이고 유용한 프롬프트를 탐색하고 사용할 수 있습니다.",
    tags: ["프롬프트", "커뮤니티"],
    filterTags: ["research", "free"],
    reason: "프롬프트 탐색 가능",
    recommendFor: ["더 좋은 AI 답변을 얻고 싶은 분", "프롬프트 엔지니어링을 공부하는 분", "다양한 AI 활용 사례를 찾는 분"],
    website: "https://flowgpt.com"
  },
  {
    id: 34,
    name: "PromptBase",
    icon: "💰",
    language: "영어",
    category: "프롬프트",
    level: "중급",
    price: "유료",
    priceType: "paid",
    description: "AI 프롬프트 마켓플레이스입니다. DALL-E, Midjourney, GPT 등을 위한 고품질 프롬프트를 구매하거나 판매할 수 있습니다.",
    tags: ["프롬프트", "마켓"],
    filterTags: ["research", "paid"],
    reason: "프롬프트 거래 플랫폼",
    recommendFor: ["검증된 고품질 프롬프트가 필요한 분", "자신만의 프롬프트를 판매하고 싶은 분", "전문적인 AI 결과물을 원하는 분"],
    website: "https://promptbase.com"
  },
  {
    id: 35,
    name: "PromptHero",
    icon: "🦸",
    language: "영어",
    category: "프롬프트",
    level: "입문",
    price: "무료",
    priceType: "free",
    description: "이미지 생성 프롬프트 탐색 도구입니다. 수많은 AI 생성 이미지와 그에 사용된 프롬프트를 확인할 수 있습니다.",
    tags: ["프롬프트", "이미지"],
    filterTags: ["research", "image", "free"],
    reason: "이미지 프롬프트 탐색",
    recommendFor: ["이미지 생성 AI 사용자", "멋진 AI 아트의 프롬프트가 궁금한 분", "시각적 영감을 얻고 싶은 분"],
    website: "https://prompthero.com"
  },
  {
    id: 36,
    name: "Writesonic",
    icon: "✍️",
    language: "한국어 지원",
    category: "글쓰기",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "AI 콘텐츠 생성 도구로, 블로그 포스트, 광고 문구, 이메일 등을 빠르게 작성할 수 있도록 도와줍니다.",
    tags: ["글쓰기", "마케팅"],
    filterTags: ["writing", "free", "korean"],
    reason: "마케팅 글 작성에 유리",
    recommendFor: ["콘텐츠 마케터", "블로그 글을 자주 쓰는 분", "글쓰기 속도를 높이고 싶은 분"],
    website: "https://writesonic.com"
  },
  {
    id: 37,
    name: "Copy AI",
    icon: "📝",
    language: "영어",
    category: "마케팅",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "마케팅 콘텐츠 생성 AI입니다. SNS 게시물, 제품 설명, 광고 카피 등을 위한 다양한 템플릿을 제공합니다.",
    tags: ["마케팅", "콘텐츠"],
    filterTags: ["writing", "free"],
    reason: "광고 카피 생성",
    recommendFor: ["SNS 운영자", "제품 상세 페이지를 만드는 분", "창의적인 마케팅 문구가 필요한 분"],
    website: "https://www.copy.ai"
  },
  {
    id: 38,
    name: "Rytr",
    icon: "✒️",
    language: "한국어 지원",
    category: "글쓰기",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "AI 글쓰기 도구입니다. 가성비 좋은 요금제와 심플한 인터페이스로 짧은 글이나 이메일 작성에 유용합니다.",
    tags: ["글쓰기", "콘텐츠"],
    filterTags: ["writing", "free", "korean"],
    reason: "간단한 글 작성",
    recommendFor: ["가벼운 글쓰기 도구를 찾는 분", "이메일 작성이 잦은 분", "가성비 좋은 AI를 원하는 분"],
    website: "https://rytr.me"
  },
  {
    id: 39,
    name: "Sudowrite",
    icon: "📖",
    language: "영어",
    category: "글쓰기",
    level: "중급",
    price: "유료",
    priceType: "paid",
    description: "창작 글쓰기 AI로, 소설가나 작가들이 스토리를 확장하고 묘사를 풍부하게 하는 데 도움을 줍니다.",
    tags: ["글쓰기", "창작"],
    filterTags: ["writing", "paid"],
    reason: "소설 창작에 적합",
    recommendFor: ["웹소설 작가", "창작 글쓰기를 하는 분", "스토리 전개가 막힌 작가"],
    website: "https://www.sudowrite.com"
  },
  {
    id: 40,
    name: "ElevenLabs",
    icon: "🔊",
    language: "한국어 지원",
    category: "음성 생성",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "AI 음성 생성 플랫폼입니다. 감정이 실린 매우 자연스러운 음성을 생성하며, 다국어 지원이 탁월합니다.",
    tags: ["TTS", "음성"],
    filterTags: ["automation", "free", "korean"],
    reason: "자연스러운 음성 생성",
    recommendFor: ["고품질 TTS가 필요한 제작자", "다국어 더빙이 필요한 분", "자연스러운 AI 목소리를 원하는 분"],
    website: "https://elevenlabs.io"
  },
  {
    id: 41,
    name: "Murf AI",
    icon: "🎙️",
    language: "영어",
    category: "음성 생성",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "AI 음성 제작 플랫폼으로, 전문 성우 수준의 목소리를 영상 콘텐츠에 입힐 수 있도록 도와줍니다.",
    tags: ["음성", "콘텐츠"],
    filterTags: ["automation", "free"],
    reason: "콘텐츠 음성 제작",
    recommendFor: ["기업 홍보 영상 제작자", "교육용 콘텐츠 개발자", "전문적인 내레이션이 필요한 분"],
    website: "https://murf.ai"
  },
  {
    id: 42,
    name: "Lovo AI",
    icon: "🗣️",
    language: "영어",
    category: "음성 생성",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "AI 보이스 생성 도구입니다. 다양한 캐릭터와 감정을 표현할 수 있는 방대한 음성 라이브러리를 제공합니다.",
    tags: ["TTS", "음성"],
    filterTags: ["automation", "free"],
    reason: "영상 음성 제작",
    recommendFor: ["유튜브 콘텐츠 제작자", "게임 캐릭터 목소리가 필요한 분", "다양한 목소리 톤을 찾는 분"],
    website: "https://lovo.ai"
  },
  {
    id: 43,
    name: "Runway",
    icon: "🎬",
    language: "영어",
    category: "영상 생성",
    level: "고급",
    price: "부분 무료",
    priceType: "free",
    description: "AI 기반 영상 생성 및 편집 플랫폼",
    tags: ["영상", "편집", "생성AI"],
    filterTags: ["automation", "free"],
    reason: "영상 생성과 편집을 동시에 지원",
    recommendFor: ["영상 제작"],
    website: "https://runwayml.com"
  },
  {
    id: 44,
    name: "Kaiber",
    icon: "🎞️",
    language: "영어",
    category: "영상 생성",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "AI 영상 생성 플랫폼으로, 음악에 맞춰 변하는 몽환적이고 예술적인 영상을 제작하는 데 특화되어 있습니다.",
    tags: ["영상", "생성AI"],
    filterTags: ["automation", "free"],
    reason: "뮤직비디오 생성",
    recommendFor: ["뮤지션 및 아티스트", "감각적인 SNS 영상을 만드는 분", "비주얼 아트 제작자"],
    website: "https://kaiber.ai"
  },
  {
    id: 45,
    name: "ClipDrop",
    icon: "📸",
    language: "영어",
    category: "이미지 편집",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "AI 이미지 편집 도구 모음입니다. 조명 조절, 배경 제거, 고해상도 변환 등 다양한 기능을 한곳에서 제공합니다.",
    tags: ["이미지", "편집"],
    filterTags: ["image", "free"],
    reason: "이미지 생성 및 편집",
    recommendFor: ["사진 보정 작업이 많은 분", "AI 이미지 생성과 편집을 동시에 하려는 분", "빠른 그래픽 작업이 필요한 분"],
    website: "https://clipdrop.co"
  },
  {
    id: 46,
    name: "DeepAI",
    icon: "🤖",
    language: "영어",
    category: "이미지 생성",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "간편하게 사용할 수 있는 AI 이미지 생성 플랫폼입니다. 다양한 스타일의 이미지를 빠르게 생성해볼 수 있습니다.",
    tags: ["이미지", "생성AI"],
    filterTags: ["image", "free"],
    reason: "간단한 이미지 생성",
    recommendFor: ["AI 이미지 생성을 가볍게 체험할 분", "빠른 시안이 필요한 분", "심플한 도구를 선호하는 분"],
    website: "https://deepai.org"
  }
];

export const extraTools: Tool[] = [
  {
    id: 101,
    name: "Suno AI",
    icon: "🎵",
    language: "한국어 지원",
    category: "음악 생성",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "텍스트만으로 고품질의 노래와 가사를 생성해주는 AI 음악 도구입니다.",
    tags: ["음악", "창작", "오디오"],
    filterTags: ["music", "free", "korean"],
    reason: "누구나 쉽게 음악을 만들 수 있는 혁신적인 도구",
    recommendFor: ["유튜버", "취미 작곡가", "나만의 노래를 만들고 싶은 분"],
    website: "https://suno.com"
  },
  {
    id: 102,
    name: "Luma Dream Machine",
    icon: "🎬",
    language: "영어",
    category: "영상 생성",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "현실적이고 역동적인 고화질 영상을 생성해주는 차세대 비디오 AI입니다.",
    tags: ["영상", "3D", "생성AI"],
    filterTags: ["video", "free"],
    reason: "영화 같은 퀄리티의 영상 제작 가능",
    recommendFor: ["영상 편집자", "콘텐츠 크리에이터", "광고 제작자"],
    website: "https://lumalabs.ai/dream-machine"
  },
  {
    id: 103,
    name: "DeepL",
    icon: "🌐",
    language: "한국어 지원",
    category: "글쓰기",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "정확한 번역과 문장 다듬기에 강한 AI 번역 도구입니다.",
    tags: ["번역", "문서", "한국어"],
    filterTags: ["writing", "free", "korean"],
    reason: "번역과 문장 교정이 필요한 사용자에게 적합",
    recommendFor: ["학생", "직장인", "번역가"],
    website: "https://www.deepl.com"
  },
  {
    id: 104,
    name: "Grammarly",
    icon: "✍️",
    language: "영어",
    category: "글쓰기",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "영문 문법 교정과 문장 스타일 개선에 특화된 AI 도구입니다.",
    tags: ["글쓰기", "교정", "문서"],
    filterTags: ["writing", "free"],
    reason: "영문 글쓰기 품질을 빠르게 높일 수 있음",
    recommendFor: ["유학생", "글로벌 비즈니스맨", "영어 작가"],
    website: "https://www.grammarly.com"
  },
  {
    id: 105,
    name: "Wordtune",
    icon: "📝",
    language: "영어",
    category: "글쓰기",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "문장을 더 자연스럽고 읽기 좋게 바꿔주는 AI 글쓰기 보조 도구입니다.",
    tags: ["문장개선", "글쓰기", "생산성"],
    filterTags: ["writing", "free"],
    reason: "문장 표현을 다듬고 싶은 사용자에게 적합",
    recommendFor: ["블로거", "카피라이터", "학생"],
    website: "https://www.wordtune.com"
  },
  {
    id: 106,
    name: "QuillBot",
    icon: "✒️",
    language: "영어",
    category: "글쓰기",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "문장 재작성과 요약 기능을 제공하는 AI 기반 글쓰기 도구입니다.",
    tags: ["요약", "재작성", "문서"],
    filterTags: ["writing", "free"],
    reason: "빠른 문장 재구성과 요약 작업에 유리",
    recommendFor: ["연구원", "학생", "콘텐츠 제작자"],
    website: "https://quillbot.com"
  },
  {
    id: 107,
    name: "Sudowrite",
    icon: "📖",
    language: "영어",
    category: "글쓰기",
    level: "중급",
    price: "유료",
    priceType: "paid",
    description: "창작 글쓰기와 스토리 아이디어 발상에 강한 AI 작문 도구입니다.",
    tags: ["창작", "소설", "아이디어"],
    filterTags: ["writing"],
    reason: "창작 중심 사용자에게 좋은 선택",
    recommendFor: ["소설가", "시나리오 작가", "창의적 작가"],
    website: "https://www.sudowrite.com"
  },
  {
    id: 108,
    name: "Writer",
    icon: "🏢",
    language: "영어",
    category: "글쓰기",
    level: "중급",
    price: "유료",
    priceType: "paid",
    description: "브랜드 톤과 문서 품질을 관리하는 기업형 AI 글쓰기 도구입니다.",
    tags: ["브랜드", "문서", "기업"],
    filterTags: ["writing"],
    reason: "팀 단위 문서 관리와 톤 유지에 적합",
    recommendFor: ["기업 마케팅팀", "콘텐츠 관리자", "기업 커뮤니케이션팀"],
    website: "https://writer.com"
  },
  {
    id: 109,
    name: "HyperWrite",
    icon: "⚡",
    language: "영어",
    category: "글쓰기",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "아이디어 확장, 이메일 작성, 문장 보완을 돕는 AI 비서입니다.",
    tags: ["글쓰기", "이메일", "생산성"],
    filterTags: ["writing", "free"],
    reason: "빠른 초안 작성이 필요한 사용자에게 적합",
    recommendFor: ["비즈니스 전문가", "이메일 업무가 많은 분", "개인 비서"],
    website: "https://www.hyperwriteai.com"
  },
  {
    id: 110,
    name: "Scalenut",
    icon: "📈",
    language: "영어",
    category: "글쓰기",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "SEO 중심 콘텐츠 작성과 최적화를 지원하는 AI 도구입니다.",
    tags: ["SEO", "콘텐츠", "마케팅"],
    filterTags: ["writing", "free"],
    reason: "검색 노출형 콘텐츠 제작에 유리",
    recommendFor: ["SEO 전문가", "디지털 마케터", "블로거"],
    website: "https://www.scalenut.com"
  },
  {
    id: 111,
    name: "Anyword",
    icon: "📣",
    language: "영어",
    category: "글쓰기",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "광고 문구와 마케팅 카피 작성에 특화된 AI 도구입니다.",
    tags: ["카피라이팅", "광고", "마케팅"],
    filterTags: ["writing", "free"],
    reason: "광고 문구 생성에 강점",
    recommendFor: ["광고 대행사", "퍼포먼스 마케터", "소상공인"],
    website: "https://anyword.com"
  },
  {
    id: 112,
    name: "INK",
    icon: "🖋️",
    language: "영어",
    category: "글쓰기",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "SEO와 카피라이팅을 함께 지원하는 AI 콘텐츠 도구입니다.",
    tags: ["SEO", "카피", "블로그"],
    filterTags: ["writing", "free"],
    reason: "검색 최적화와 글쓰기를 함께 챙길 수 있음",
    recommendFor: ["콘텐츠 전략가", "웹 마스터", "프리랜서 작가"],
    website: "https://inkforall.com"
  },
  {
    id: 113,
    name: "Elicit",
    icon: "🔍",
    language: "영어",
    category: "리서치",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "논문 검색과 연구 자료 정리를 돕는 AI 리서치 도구입니다.",
    tags: ["논문", "연구", "검색"],
    filterTags: ["research", "free"],
    reason: "학술 리서치 작업에 유용",
    recommendFor: ["대학원생", "학술 연구원", "지식 탐구자"],
    website: "https://elicit.org"
  },
  {
    id: 114,
    name: "Consensus",
    icon: "🤝",
    language: "영어",
    category: "리서치",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "연구 논문 기반으로 답변을 정리해주는 AI 검색 도구입니다.",
    tags: ["논문", "검색", "요약"],
    filterTags: ["research", "free"],
    reason: "근거 기반 리서치에 적합",
    recommendFor: ["팩트 체크가 필요한 분", "과학 저널리스트", "학생"],
    website: "https://consensus.app"
  },
  {
    id: 115,
    name: "Scite",
    icon: "📑",
    language: "영어",
    category: "리서치",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "논문 인용 맥락을 분석해 신뢰도 높은 참고 자료를 찾게 도와줍니다.",
    tags: ["논문", "인용", "연구"],
    filterTags: ["research", "free"],
    reason: "논문 신뢰도 확인에 강점",
    recommendFor: ["학술 저자", "리뷰어", "연구 관리자"],
    website: "https://scite.ai"
  },
  {
    id: 116,
    name: "Research Rabbit",
    icon: "🐰",
    language: "영어",
    category: "리서치",
    level: "입문",
    price: "무료",
    priceType: "free",
    description: "연구 주제와 관련된 논문 네트워크를 시각적으로 탐색할 수 있습니다.",
    tags: ["논문", "시각화", "연구"],
    filterTags: ["research", "free"],
    reason: "연구 흐름을 한눈에 보기 좋음",
    recommendFor: ["논문 초심자", "연구 기획자", "도서관 사서"],
    website: "https://www.researchrabbit.ai"
  },
  {
    id: 117,
    name: "Scholarcy",
    icon: "🎓",
    language: "영어",
    category: "리서치",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "긴 논문과 보고서를 빠르게 핵심만 정리해주는 AI 요약 도구입니다.",
    tags: ["요약", "논문", "문서"],
    filterTags: ["research", "free"],
    reason: "긴 자료를 빠르게 정리하기 좋음",
    recommendFor: ["바쁜 연구원", "정책 분석가", "학생"],
    website: "https://www.scholarcy.com"
  },
  {
    id: 118,
    name: "Humata",
    icon: "📄",
    language: "영어",
    category: "리서치",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "문서를 업로드하고 질문하며 내용을 빠르게 파악할 수 있는 AI 도구입니다.",
    tags: ["PDF", "질문응답", "문서"],
    filterTags: ["research", "free"],
    reason: "PDF 기반 질의응답에 적합",
    recommendFor: ["법률 전문가", "금융 분석가", "학생"],
    website: "https://www.humata.ai"
  },
  {
    id: 119,
    name: "AskYourPDF",
    icon: "📂",
    language: "영어",
    category: "리서치",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "PDF 문서 내용을 대화형으로 탐색할 수 있는 AI 도구입니다.",
    tags: ["PDF", "대화형", "문서"],
    filterTags: ["research", "free"],
    reason: "문서 읽기 시간을 크게 줄여줌",
    recommendFor: ["학습자", "정보 분석가", "일반 사용자"],
    website: "https://askyourpdf.com"
  },
  {
    id: 120,
    name: "Semantic Scholar",
    icon: "🧠",
    language: "영어",
    category: "리서치",
    level: "입문",
    price: "무료",
    priceType: "free",
    description: "학술 논문 검색과 연구 탐색을 지원하는 플랫폼입니다.",
    tags: ["논문", "검색", "학술"],
    filterTags: ["research", "free"],
    reason: "학술 검색 기본 도구로 활용 가능",
    recommendFor: ["모든 연구자", "대학생", "교수"],
    website: "https://www.semanticscholar.org"
  },
  {
    id: 121,
    name: "Explainpaper",
    icon: "💡",
    language: "영어",
    category: "리서치",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "어려운 논문 내용을 쉽게 풀어 설명해주는 AI 학습 도구입니다.",
    tags: ["논문", "설명", "학습"],
    filterTags: ["research", "free"],
    reason: "복잡한 논문 이해를 도와줌",
    recommendFor: ["학부생", "비전공자", "과학 입문자"],
    website: "https://www.explainpaper.com"
  },
  {
    id: 122,
    name: "Wolfram Alpha",
    icon: "🔢",
    language: "영어",
    category: "리서치",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "수학, 과학, 계산 중심 질문에 강한 지식형 AI 도구입니다.",
    tags: ["계산", "과학", "문제해결"],
    filterTags: ["research", "free"],
    reason: "정확한 계산과 개념 확인에 유리",
    recommendFor: ["공대생", "수학자", "데이터 분석가"],
    website: "https://www.wolframalpha.com"
  },
  {
    id: 123,
    name: "Leonardo AI",
    icon: "🎨",
    language: "영어",
    category: "이미지",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "일러스트와 게임풍 이미지를 만들기 좋은 생성형 AI 도구입니다.",
    tags: ["이미지생성", "일러스트", "디자인"],
    filterTags: ["image", "free"],
    reason: "크리에이티브 이미지 생성에 강점",
    recommendFor: ["게임 디자이너", "일러스트레이터", "취미 예술가"],
    website: "https://leonardo.ai"
  },
  {
    id: 124,
    name: "Ideogram",
    icon: "🔠",
    language: "영어",
    category: "이미지",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "텍스트가 잘 들어간 이미지 생성에 특화된 AI 도구입니다.",
    tags: ["이미지생성", "텍스트", "포스터"],
    filterTags: ["image", "free"],
    reason: "문구가 들어간 이미지 제작에 적합",
    recommendFor: ["그래픽 디자이너", "마케터", "타이포그래퍼"],
    website: "https://ideogram.ai"
  },
  {
    id: 125,
    name: "Adobe Firefly",
    icon: "🔥",
    language: "영어",
    category: "이미지",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "어도비 생태계와 연동되는 생성형 이미지 AI 도구입니다.",
    tags: ["이미지생성", "디자인", "어도비"],
    filterTags: ["image", "free"],
    reason: "디자인 작업과 연동성이 좋음",
    recommendFor: ["포토샵 사용자", "디자인 전문가", "크리에이티브 디렉터"],
    website: "https://www.adobe.com/sensei/generative-ai/firefly.html"
  },
  {
    id: 126,
    name: "Playground AI",
    icon: "🎡",
    language: "영어",
    category: "이미지",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "간편하게 이미지 생성과 편집을 할 수 있는 AI 플랫폼입니다.",
    tags: ["이미지", "편집", "생성AI"],
    filterTags: ["image", "free"],
    reason: "가볍게 이미지 작업하기 좋음",
    recommendFor: ["SNS 관리자", "블로거", "일반 사용자"],
    website: "https://playgroundai.com"
  },
  {
    id: 127,
    name: "DreamStudio",
    icon: "🌌",
    language: "영어",
    category: "이미지",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "Stable Diffusion 기반 이미지 생성을 지원하는 공식 도구입니다.",
    tags: ["StableDiffusion", "이미지", "생성AI"],
    filterTags: ["image", "free"],
    reason: "Stable Diffusion 입문용으로 적합",
    recommendFor: ["AI 아티스트", "기술적 디자이너", "연구자"],
    website: "https://dreamstudio.ai"
  },
  {
    id: 128,
    name: "Canva Magic Media",
    icon: "✨",
    language: "한국어 지원",
    category: "이미지",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "Canva 안에서 이미지 생성과 편집을 빠르게 수행할 수 있습니다.",
    tags: ["디자인", "이미지", "Canva"],
    filterTags: ["image", "free", "korean"],
    reason: "프레젠테이션과 SNS 디자인에 유리",
    recommendFor: ["프레젠테이션 제작자", "SNS 마케터", "비전문 디자이너"],
    website: "https://www.canva.com/magic-home/"
  },
  {
    id: 129,
    name: "Clipdrop",
    icon: "✂️",
    language: "영어",
    category: "이미지",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "배경 제거, 업스케일, 객체 수정 등 이미지 편집에 강한 AI 도구입니다.",
    tags: ["편집", "배경제거", "이미지"],
    filterTags: ["image", "free"],
    reason: "실무형 이미지 보정에 적합",
    recommendFor: ["이커머스 운영자", "사진 편집자", "웹 디자이너"],
    website: "https://clipdrop.co"
  },
  {
    id: 130,
    name: "Remove.bg",
    icon: "🖼️",
    language: "영어",
    category: "이미지",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "사진 속 배경을 빠르게 제거해주는 AI 기반 편집 도구입니다.",
    tags: ["배경제거", "편집", "디자인"],
    filterTags: ["image", "free"],
    reason: "배경 제거 작업을 자동화할 수 있음",
    recommendFor: ["쇼핑몰 사장님", "디자이너", "일반 사용자"],
    website: "https://www.remove.bg"
  },
  {
    id: 131,
    name: "Magnific AI",
    icon: "💎",
    language: "영어",
    category: "이미지",
    level: "중급",
    price: "유료",
    priceType: "paid",
    description: "저해상도 이미지를 선명하게 업스케일링하는 AI 도구입니다.",
    tags: ["업스케일", "이미지", "보정"],
    filterTags: ["image"],
    reason: "이미지 품질 개선에 강함",
    recommendFor: ["전문 사진작가", "인쇄물 디자이너", "고화질 선호자"],
    website: "https://magnific.ai"
  },
  {
    id: 132,
    name: "Krea AI",
    icon: "🎭",
    language: "영어",
    category: "이미지",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "실시간으로 이미지 스타일을 탐색하고 생성할 수 있는 AI 도구입니다.",
    tags: ["실시간생성", "스타일", "이미지"],
    filterTags: ["image", "free"],
    reason: "스타일 탐색과 시각 실험에 적합",
    recommendFor: ["컨셉 아티스트", "비주얼 디자이너", "실험적 예술가"],
    website: "https://www.krea.ai"
  },
  {
    id: 133,
    name: "Pika",
    icon: "🎬",
    language: "영어",
    category: "영상",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "텍스트와 이미지로 짧은 영상을 생성할 수 있는 AI 도구입니다.",
    tags: ["영상생성", "숏폼", "생성AI"],
    filterTags: ["video", "free"],
    reason: "짧은 영상 제작 입문용으로 좋음",
    recommendFor: ["틱톡커", "릴스 제작자", "영상 입문자"],
    website: "https://pika.art"
  },
  {
    id: 134,
    name: "Synthesia",
    icon: "👤",
    language: "한국어 지원",
    category: "영상",
    level: "중급",
    price: "유료",
    priceType: "paid",
    description: "AI 아바타를 활용해 설명형 영상을 제작할 수 있는 플랫폼입니다.",
    tags: ["아바타", "영상", "프레젠테이션"],
    filterTags: ["video", "korean"],
    reason: "설명형 비디오 제작에 강점",
    recommendFor: ["L&D 전문가", "기업 교육 담당자", "유튜버"],
    website: "https://www.synthesia.io"
  },
  {
    id: 135,
    name: "HeyGen",
    icon: "👋",
    language: "한국어 지원",
    category: "영상",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "AI 아바타와 음성을 이용해 발표형 영상을 만들 수 있습니다.",
    tags: ["아바타", "영상", "콘텐츠"],
    filterTags: ["video", "free", "korean"],
    reason: "발표형 콘텐츠 제작에 적합",
    recommendFor: ["마케터", "교육자", "콘텐츠 크리에이터"],
    website: "https://www.heygen.com"
  },
  {
    id: 136,
    name: "Descript",
    icon: "🎙️",
    language: "영어",
    category: "영상",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "텍스트를 수정하듯 영상과 오디오를 편집할 수 있는 AI 도구입니다.",
    tags: ["편집", "오디오", "영상"],
    filterTags: ["video", "free"],
    reason: "편집 흐름이 직관적이고 빠름",
    recommendFor: ["팟캐스터", "비디오 에디터", "콘텐츠 팀"],
    website: "https://www.descript.com"
  },
  {
    id: 137,
    name: "Kapwing",
    icon: "🎞️",
    language: "한국어 지원",
    category: "영상",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "자막, 편집, 리사이즈 등 영상 제작 전반을 지원하는 온라인 도구입니다.",
    tags: ["편집", "자막", "콘텐츠"],
    filterTags: ["video", "free", "korean"],
    reason: "숏폼 콘텐츠 제작에 유리",
    recommendFor: ["소셜 미디어 관리자", "학생", "초보 편집자"],
    website: "https://www.kapwing.com"
  },
  {
    id: 138,
    name: "Opus Clip",
    icon: "✂️",
    language: "영어",
    category: "영상",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "긴 영상을 짧은 클립으로 자동 변환해주는 AI 도구입니다.",
    tags: ["숏폼", "자동편집", "영상"],
    filterTags: ["video", "free"],
    reason: "롱폼을 숏폼으로 전환할 때 효율적",
    recommendFor: ["유튜버", "팟캐스터", "디지털 마케터"],
    website: "https://www.opus.pro"
  },
  {
    id: 139,
    name: "VEED",
    icon: "📹",
    language: "한국어 지원",
    category: "영상",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "자막 생성과 기본 편집 기능이 강한 온라인 영상 편집 도구입니다.",
    tags: ["자막", "편집", "영상"],
    filterTags: ["video", "free", "korean"],
    reason: "자막 중심 영상 제작에 적합",
    recommendFor: ["콘텐츠 제작자", "교육용 영상 제작자", "마케터"],
    website: "https://www.veed.io"
  },
  {
    id: 140,
    name: "Filmora AI",
    icon: "🎬",
    language: "한국어 지원",
    category: "영상",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "초보자도 쉽게 다룰 수 있는 AI 보조 영상 편집 도구입니다.",
    tags: ["편집", "초보자", "영상"],
    filterTags: ["video", "free", "korean"],
    reason: "입문자 친화적인 영상 제작 도구",
    recommendFor: ["영상 입문자", "가족 영상 제작자", "학생"],
    website: "https://filmora.wondershare.net"
  },
  {
    id: 141,
    name: "Udio",
    icon: "🎵",
    language: "영어",
    category: "음악",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "보컬과 분위기 표현이 자연스러운 AI 음악 생성 도구입니다.",
    tags: ["음악", "보컬", "생성AI"],
    filterTags: ["music", "free"],
    reason: "완성도 있는 음악 생성에 강점",
    recommendFor: ["작곡가", "음악 프로듀서", "콘텐츠 제작자"],
    website: "https://www.udio.com"
  },
  {
    id: 142,
    name: "AIVA",
    icon: "🎼",
    language: "영어",
    category: "음악",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "배경음악과 감성 중심 작곡에 강한 AI 음악 도구입니다.",
    tags: ["작곡", "배경음악", "음악"],
    filterTags: ["music", "free"],
    reason: "영상용 배경음악 제작에 적합",
    recommendFor: ["영화 제작자", "유튜버", "게임 개발자"],
    website: "https://www.aiva.ai"
  },
  {
    id: 143,
    name: "Mubert",
    icon: "🎧",
    language: "영어",
    category: "음악",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "스트리밍용 배경음악을 자동 생성해주는 AI 음악 도구입니다.",
    tags: ["배경음악", "스트리밍", "음악"],
    filterTags: ["music", "free"],
    reason: "무드 기반 배경음 제작에 유리",
    recommendFor: ["스트리머", "앱 개발자", "공간 운영자"],
    website: "https://mubert.com"
  },
  {
    id: 144,
    name: "Boomy",
    icon: "💥",
    language: "영어",
    category: "음악",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "초보자도 쉽게 음악을 생성하고 공유할 수 있는 플랫폼입니다.",
    tags: ["음악", "작곡", "초보자"],
    filterTags: ["music", "free"],
    reason: "간편한 음악 생성에 적합",
    recommendFor: ["음악 입문자", "SNS 사용자", "일반인"],
    website: "https://boomy.com"
  },
  {
    id: 145,
    name: "Beatoven",
    icon: "🥁",
    language: "영어",
    category: "음악",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "분위기와 장면에 맞는 배경음악을 만드는 AI 도구입니다.",
    tags: ["배경음", "영상음악", "생성AI"],
    filterTags: ["music", "free"],
    reason: "영상 분위기 맞춤 음원 제작 가능",
    recommendFor: ["영상 편집자", "광고 제작자", "스토리텔러"],
    website: "https://www.beatoven.ai"
  },
  {
    id: 146,
    name: "ElevenLabs",
    icon: "🗣️",
    language: "한국어 지원",
    category: "음성",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "자연스러운 AI 음성 합성과 더빙에 강한 음성 생성 도구입니다.",
    tags: ["TTS", "음성", "더빙"],
    filterTags: ["voice", "free", "korean"],
    reason: "고품질 음성 생성이 가능",
    recommendFor: ["오디오북 제작자", "유튜버", "더빙 전문가"],
    website: "https://elevenlabs.io"
  },
  {
    id: 147,
    name: "Murf",
    icon: "🎙️",
    language: "한국어 지원",
    category: "음성",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "프레젠테이션과 내레이션용 AI 음성을 만들 수 있는 도구입니다.",
    tags: ["내레이션", "음성", "프레젠테이션"],
    filterTags: ["voice", "free", "korean"],
    reason: "발표나 설명 영상 음성 제작에 적합",
    recommendFor: ["교육 담당자", "마케터", "발표자"],
    website: "https://murf.ai"
  },
  {
    id: 148,
    name: "PlayHT",
    icon: "🔊",
    language: "한국어 지원",
    category: "음성",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "다양한 AI 보이스와 음성 API를 제공하는 음성 생성 플랫폼입니다.",
    tags: ["보이스", "TTS", "API"],
    filterTags: ["voice", "free", "korean"],
    reason: "음성 서비스 확장에 유리",
    recommendFor: ["앱 개발자", "웹 마스터", "콘텐츠 팀"],
    website: "https://play.ht"
  },
  {
    id: 149,
    name: "Speechify",
    icon: "📖",
    language: "한국어 지원",
    category: "음성",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "문서를 자연스럽게 읽어주는 AI 음성 읽기 도구입니다.",
    tags: ["음성읽기", "문서", "생산성"],
    filterTags: ["voice", "free", "korean"],
    reason: "텍스트를 듣고 학습하는 데 유용",
    recommendFor: ["학생", "독서 애호가", "시각 장애인"],
    website: "https://speechify.com"
  },
  {
    id: 150,
    name: "Resemble AI",
    icon: "👥",
    language: "영어",
    category: "음성",
    level: "중급",
    price: "유료",
    priceType: "paid",
    description: "맞춤형 음성 생성과 음성 복제 기능을 제공하는 플랫폼입니다.",
    tags: ["보이스클론", "음성", "API"],
    filterTags: ["voice"],
    reason: "커스텀 음성 제작에 적합",
    recommendFor: ["브랜드 매니저", "게임 개발자", "기술팀"],
    website: "https://www.resemble.ai"
  },
  {
    id: 151,
    name: "Speechmatics",
    icon: "📝",
    language: "한국어 지원",
    category: "음성",
    level: "중급",
    price: "유료",
    priceType: "paid",
    description: "정확도 높은 음성 인식과 전사 기능을 제공하는 도구입니다.",
    tags: ["STT", "전사", "음성"],
    filterTags: ["voice", "korean"],
    reason: "회의 전사와 자막 작업에 적합",
    recommendFor: ["속기사", "방송 제작팀", "데이터 분석가"],
    website: "https://www.speechmatics.com"
  },
  {
    id: 152,
    name: "Replit AI",
    icon: "🚀",
    language: "영어",
    category: "코딩",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "브라우저 기반 개발 환경에서 코딩을 보조하는 AI 도구입니다.",
    tags: ["개발", "코드생성", "협업"],
    filterTags: ["coding", "free"],
    reason: "간단한 개발과 실습에 편리",
    recommendFor: ["초보 개발자", "학생", "프로토타이핑"],
    website: "https://replit.com"
  },
  {
    id: 153,
    name: "Codeium",
    icon: "💻",
    language: "영어",
    category: "코딩",
    level: "입문",
    price: "무료",
    priceType: "free",
    description: "다양한 IDE에서 사용할 수 있는 AI 코드 자동완성 도구입니다.",
    tags: ["자동완성", "개발", "코딩"],
    filterTags: ["coding", "free"],
    reason: "무료 코드 보조 도구로 강력함",
    recommendFor: ["모든 개발자", "오픈소스 기여자", "학생"],
    website: "https://codeium.com"
  },
  {
    id: 154,
    name: "Tabnine",
    icon: "⌨️",
    language: "영어",
    category: "코딩",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "개발 생산성을 높여주는 AI 코드 추천 도구입니다.",
    tags: ["자동완성", "코드추천", "개발"],
    filterTags: ["coding", "free"],
    reason: "반복 코딩 시간을 줄여줌",
    recommendFor: ["현업 개발자", "엔지니어링 팀", "학생"],
    website: "https://www.tabnine.com"
  },
  {
    id: 155,
    name: "Sourcegraph Cody",
    icon: "🕵️",
    language: "영어",
    category: "코딩",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "대규모 코드베이스 탐색과 이해를 돕는 AI 개발 도구입니다.",
    tags: ["코드검색", "개발", "리포지토리"],
    filterTags: ["coding", "free"],
    reason: "큰 프로젝트 분석에 유리",
    recommendFor: ["시니어 개발자", "아키텍트", "코드 리뷰어"],
    website: "https://about.sourcegraph.com/cody"
  },
  {
    id: 156,
    name: "Phind",
    icon: "🔎",
    language: "영어",
    category: "코딩",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "개발자 질문에 특화된 AI 검색과 답변 도구입니다.",
    tags: ["개발검색", "질문응답", "코딩"],
    filterTags: ["coding", "free"],
    reason: "개발 문제 해결 속도를 높여줌",
    recommendFor: ["트러블슈팅이 필요한 개발자", "학습자", "엔지니어"],
    website: "https://www.phind.com"
  },
  {
    id: 157,
    name: "Amazon CodeWhisperer",
    icon: "☁️",
    language: "영어",
    category: "코딩",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "AWS 환경과 연동되는 AI 코드 추천 도구입니다.",
    tags: ["AWS", "자동완성", "개발"],
    filterTags: ["coding", "free"],
    reason: "AWS 개발자에게 특히 유용",
    recommendFor: ["AWS 클라우드 엔지니어", "백엔드 개발자", "DevOps"],
    website: "https://aws.amazon.com/codewhisperer/"
  },
  {
    id: 158,
    name: "Make",
    icon: "🔗",
    language: "영어",
    category: "자동화",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "앱 간 워크플로를 시각적으로 연결하는 자동화 플랫폼입니다.",
    tags: ["워크플로", "자동화", "생산성"],
    filterTags: ["automation", "free"],
    reason: "복잡한 자동화 시나리오 구성에 강함",
    recommendFor: ["운영 전문가", "비즈니스 분석가", "노코드 개발자"],
    website: "https://www.make.com"
  },
  {
    id: 159,
    name: "IFTTT",
    icon: "⚡",
    language: "영어",
    category: "자동화",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "간단한 조건 기반 자동화를 쉽게 만들 수 있는 플랫폼입니다.",
    tags: ["자동화", "연동", "생산성"],
    filterTags: ["automation", "free"],
    reason: "초보자도 쉽게 자동화를 시작할 수 있음",
    recommendFor: ["스마트홈 사용자", "일반 사용자", "마케터"],
    website: "https://ifttt.com"
  },
  {
    id: 160,
    name: "n8n",
    icon: "🕸️",
    language: "영어",
    category: "자동화",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "개발 친화적인 워크플로 자동화를 지원하는 오픈형 도구입니다.",
    tags: ["워크플로", "오픈소스", "자동화"],
    filterTags: ["automation", "free"],
    reason: "유연한 자동화 구성이 가능",
    recommendFor: ["기술적 자동화 전문가", "개발자", "IT 관리자"],
    website: "https://n8n.io"
  },
  {
    id: 161,
    name: "Bardeen",
    icon: "🪄",
    language: "영어",
    category: "자동화",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "브라우저 작업과 반복 업무를 자동화하는 AI 도구입니다.",
    tags: ["브라우저", "자동화", "생산성"],
    filterTags: ["automation", "free"],
    reason: "반복 클릭과 복사 작업 자동화에 유리",
    recommendFor: ["영업 담당자", "리서처", "개인 생산성 추구자"],
    website: "https://www.bardeen.ai"
  },
  {
    id: 162,
    name: "Taskade",
    icon: "📋",
    language: "한국어 지원",
    category: "자동화",
    level: "입문",
    price: "부분 무료",
    priceType: "free",
    description: "AI와 협업 기능을 결합한 업무 관리 및 자동화 도구입니다.",
    tags: ["협업", "생산성", "자동화"],
    filterTags: ["automation", "free", "korean"],
    reason: "팀 협업과 AI 업무 정리에 적합",
    recommendFor: ["팀 리더", "프로젝트 매니저", "프리랜서"],
    website: "https://www.taskade.com"
  },
  {
    id: 163,
    name: "ClickUp AI",
    icon: "🖱️",
    language: "영어",
    category: "자동화",
    level: "중급",
    price: "부분 무료",
    priceType: "free",
    description: "프로젝트 관리와 문서, 작업 흐름을 함께 다루는 AI 업무 도구입니다.",
    tags: ["업무관리", "협업", "생산성"],
    filterTags: ["automation", "free"],
    reason: "업무 관리와 AI 기능을 함께 쓰기 좋음",
    recommendFor: ["PM", "운영팀", "스타트업"],
    website: "https://clickup.com/ai"
  }
];


export const allTools = [...tools, ...extraTools];
export const TOOL_COUNT = allTools.length;
